1st version
Anarmard/java-shareit pull request #1
Opened 2023-01-06 01:02 UTC by Anarmard

Add User & Item 

Difficulties:
- ExceptionHandler
- toLowerCase

2023-01-09 22:38 UTC, alexache requested changes

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item; // вещь, которую пользователь бронирует
В ДТО классах не стоит ссылаться на классы-модели. Должно быть четкое разделение ДТО и моделей

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        Item returnedItem = itemService.addNewItem(userId, currentItem);
Разве в самом объекте Item уже нет userId? Нужно ли отдельно передавать его в сервис

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        ALL_ITEMS.remove(findByItemId(itemId));
Может лучше обойтись одним единственным методом removeIf?

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        for (int id = 1; id <= ALL_ITEMS.size(); id++) {
Может все же лучше хранить как-то по-другому, чтобы не было поиска по всему списку?

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        List<Item> allUserItems = new ArrayList<>();
И тут полный поиск по списку, лучше бы хранить 2 "индекса"-мапы. вещь по айди вещи и список вещей по юзеру

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +            if (((currentItem.getName().toLowerCase().contains(text.toLowerCase()))
text.toLowerCase() можно вызвать единожды до цикла

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +                ALL_ITEMS.remove(currentItem);
Можно заменить на removeIf

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    public boolean checkUserOwnsItem(long userId, long itemId) {
Вместо такой проверки вероятно будет достаточно использовать findByItemId и проверять свойство. Предполагаю, что иначе вызов поиска по айди будет сделан много раз

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        userService.getUserById(userId);
getUserById вызывается несколько раз, разве userId и item.getOwner().getId() не равны, согласно мапперу?

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +/**
Такие комментарии лучше удалять, либо менять на осмысленное содержимое

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +public class ItemController extends ErrorHandler {
А для чего расширять ErrorHandler? Разве спринг сам не разберется с @RestControllerAdvice?

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    private static final List<User> ALL_USERS = new ArrayList<>();
Тут тоже посоветовал бы воспользоваться мапой вместо списка

2023-01-09 22:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +            if (Objects.equals(user.getEmail(), ALL_USERS.get(id - 1).getEmail())) {
Что если вызвать метод обновления пользователя с тем же емейлом, что и до того. проверка не пройдет?
К тому же, опять полный проход по списку, что печально :(

2023-01-11 22:46 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item; // вещь, которую пользователь бронирует
Понял, поправил. Спасибо

2023-01-11 22:56 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        userService.getUserById(userId);
Даже не могу объяснить зачем эта строчка нужна... Спасибо, удалил, это лишнее

2023-01-11 23:01 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +/**
Эти комментарии уже были в проекте, думал, что нельзя их удалять. Я их тогда удалю...
Но, если ты не возражаешь, оставлю комментарии  "TODO Sprint add-item-requests" и "TODO Sprint add-bookings" (чтобы в ТЗ14 и ТЗ15 понимать, где нужно писать код)?

2023-01-11 23:02 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        Item returnedItem = itemService.addNewItem(userId, currentItem);
Точно) не нужно так делать. Поправил, спасибо!

2023-01-11 23:12 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        ALL_ITEMS.remove(findByItemId(itemId));
Надеюсь верно использовал метод removeIf...

2023-01-11 23:15 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +            if (((currentItem.getName().toLowerCase().contains(text.toLowerCase()))
Спасибо, поправил!

2023-01-11 23:27 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +                ALL_ITEMS.remove(currentItem);
Сделано, спасибо

2023-01-12 00:17 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    public boolean checkUserOwnsItem(long userId, long itemId) {
Александр, поправил, надеюсь верно понял комментарий.

2023-01-12 00:36 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +            if (Objects.equals(user.getEmail(), ALL_USERS.get(id - 1).getEmail())) {
Да, неверная логика у меня была. Добавил доп условие, что проверка не будет пройдена, если у пользователей с разным ID, будет одинаковый email. 
List поменял на HashMap и где смог убрал лишние проходы по всему списку/таблице.

2023-01-12 01:21 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    private static final List<User> ALL_USERS = new ArrayList<>();
Да, спасибо, поправил

2023-01-12 01:27 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +public class ItemController extends ErrorHandler {
Понял, спасибо. Убрал лишнее.

2023-01-12 02:06 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        for (int id = 1; id <= ALL_ITEMS.size(); id++) {
Поправил

2023-01-12 02:07 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        List<Item> allUserItems = new ArrayList<>();
Александр, я поменял на 2 мапы, если верно понял твой совет.

2023-01-13 11:35 UTC, alexache requested changes

2023-01-13 11:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        USER_ID_ITEM_LIST_MAP.get(item.getOwner().getId()).removeIf(n -> Objects.equals(n, item));
(опционально) equals будет достаточно делать по айди вещи, а не полному соответствию объекта. Пока это не важно. но в будушем будет нагляднее

2023-01-13 11:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        ID_ITEM_MAP.remove(itemId);
А зачем его удалять, если можно просто вызвать сеттеры, как ниже и делается на том же объекте, что уже хранится? Тогда будет достаточно  получения объекта из первой мапы (сам объект один и тот же в обоих мапах)

2023-01-13 11:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        ID_ITEM_MAP.put(itemId, savedItem);
При текущем подходе с удалением - не вижу сохранения его в мапу вещей юзера, а удаление есть. В идеале вообще не удалять

2023-01-13 11:35 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        if (ID_ITEM_MAP.containsKey(itemId)) {
(очень опционально) Если очень нравится функциональный подход, то можно писать что-то вроде Optional.ofNullable(ID_ITEM_MAP.get(itemId)).orElseThrow(() -> new NotFundException(""));

2023-01-13 18:28 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        if (ID_ITEM_MAP.containsKey(itemId)) {
Спасибо за оптимизацию кода, поправил)

2023-01-13 18:48 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        USER_ID_ITEM_LIST_MAP.get(item.getOwner().getId()).removeIf(n -> Objects.equals(n, item));
Ок, поменял на следующий код:
n -> Objects.equals(n.getId(), item.getId())

2023-01-13 18:53 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        ID_ITEM_MAP.remove(itemId);
Точно!!! Причем ты меня уже так исправлял в предыдущих спринтах. Не могу никак усвоить, что в мапах хранится **ссылка** на объект, а не сам объект.... Спасибо большое, обновил код!

2023-01-13 18:58 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        ID_ITEM_MAP.put(itemId, savedItem);
Поправил, спасибо! 
Аналогичные правки внес в UserRepository

2023-01-15 08:36 UTC, alexache approved these changes

2023-01-15 11:23 UTC, merged