v1.0
Anarmard/java-shareit pull request #2
Opened 2023-01-23 02:48 UTC by Anarmard

- add booking and comments
- DB instead of memory

Проблема: даты в booking. Формат

2023-01-24 06:38 UTC, alexache requested changes

2023-01-24 06:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateRequestDto.java
> +    @NotBlank
@NotBlank не очень применимы для дат, лучше использовать @Future, @FutureOrPresent и прочие более релевантные

2023-01-24 06:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Timestamp currentMoment = Timestamp.valueOf(LocalDateTime.now());
Почему Timestamp?  Лучше не отходить нигде от LocalDateTime, с остальным Hibernate справится

2023-03-01 00:09 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateRequestDto.java
> +    @NotBlank
спасибо, поправил

2023-03-01 00:10 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Timestamp currentMoment = Timestamp.valueOf(LocalDateTime.now());
Спасибо за совет, исправил!

2023-03-05 23:34 UTC, Anarmard commented
Александр, привет! За эту неделю пока правил программу, узнал, что если проходят все тесты в Postman, тесты на гитхабе могут не проходить. Ошибка была в том, что в объектах Item и Comment я указал неверные названия столбцов... Не понимаю тогда, почему тесты в постмане проходились.

2023-03-06 20:58 UTC, alexache requested changes

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        userService.getUserById(userId);
(опционально) на мой взгляд, выходит слишком много логики для контроллера - столько коммуникации между вызовами-мапперы-другие сущности лучше решать в сервисе, а из сервиса вызывать репозитории соответствующих сущностей

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateRequestDto.java
> +@Valid
Обычно эту аннотацию ставят в контроллере непосредственно на аргумент

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +@Valid
А для ответа от контроллера применимость данной аннотации сомнительна

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b " +
(опционально) Многие (если не все) запросы из кастомных @Query здесь можно бы реализовать через именование методов, как в случае с самым первым методом репозитория выше. Запрос будет немного сложнее, и есть пределы, когда это перестает быть целесообразно (длина метода превышает разумные границы)

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        BookingState stateBooking = Objects.isNull(state) ? BookingState.ALL : BookingState.of(state);
(опционально) это можно решать выставлением значений по умолчанию у аргументов контроллера

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreateRequestDto.java
> +    private User authorName;
Наличие неДТО полей в ДТО классе не очень хороший знак. Лучше разделять модели и ДТО так, чтобы они не смешивались

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemBookingResponseDto> getItemsBooking(Long userId);
Тоже смешивание ДТО и моделей в  качестве возвращаемого типа в одном интерфесе, что выглядит немного настораживающе

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<Booking> lastListBooking = bookingRepository.findLastBooking(itemFromDB, BookingStatus.APPROVED, LocalDateTime.now());
Интересно, отчего метод возвращения последнего бронирования может возвращать список

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemBookingResponseDtoList.add(getItemBooking(itemFromDB.getId(), userId));
Запросы к базе в цикле под большим табу, потому что это выглядит с виду просто, а по факту очень непредсказуемый рост затрат по времени и ресурсам. Обычно это обходится отдельным запросом к базе со списком сущностей - получить последний бронирования для списка товаров и дальнейшей соответствующей обработки уже в джаве

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return getItem(item.getId());
Для чего отдельный запрос следом? Почему не подсмотреть айди сущности в ответе от репозитория?

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (bookingRepository.findPastByBooker(comment.getAuthor(), LocalDateTime.now()).isEmpty()) {
Хорошо бы еще проверять, что автор комментария имел бронирования именно той же вещи, что и вещь в комментарии

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    //@SequenceGenerator(name = "pk_sequence", schema = "public", sequenceName = "requests_id_seq", allocationSize = 1)
Закомментированный код лучше подчищать

2023-03-06 20:58 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (User u: getAllUsers()) {
Сложный способ. а отчего бы не сделать запрос к базе для поиска юзера по имейлу?

2023-03-09 22:29 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    //@SequenceGenerator(name = "pk_sequence", schema = "public", sequenceName = "requests_id_seq", allocationSize = 1)
Да, извини, забыл убрать в этом разделе.

2023-03-09 22:41 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return getItem(item.getId());
Правил эту строку, когда искал ошибку. Сейчас вернул как было, ошибок вроде нет.

2023-03-09 22:48 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateRequestDto.java
> +@Valid
Получается это здесь лишнее (в контроллере данную аннотацию использую). Убрал. Спасибо, Александр!

2023-03-09 22:48 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +@Valid
Получается в ответных dto странно использовать аннотацию valid. Убрал. Спасибо, Александр!

2023-03-09 22:51 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreateRequestDto.java
> +    private User authorName;
Да, точно! Спасибо! исправил

2023-03-09 23:03 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b " +
Если честно я начинал писать запросы через именование методов (запросные методы). Но на каких-то запросах вылетали ошибки, потратил время на их исправление, в итоге написал как подсказал наставник. Я попробую снова переписать их на запросные, но не обещаю, что смогу их все переписать.

2023-03-09 23:31 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<Booking> lastListBooking = bookingRepository.findLastBooking(itemFromDB, BookingStatus.APPROVED, LocalDateTime.now());
Я пробовал ограничить выдачу запроса 1 элементом (через limit 1), но не сработало.... Как я понял с форума: 
JPQL (то, что использую я вместо запросных методов) не поддерживает выдачу лимитированного ответа. Предлагают написать запросный метод.

2023-03-10 23:12 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (User u: getAllUsers()) {
Да, спасибо за совет! Поправил.

2023-03-10 23:36 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (bookingRepository.findPastByBooker(comment.getAuthor(), LocalDateTime.now()).isEmpty()) {
Да, конечно! не проверял, что именно комментируемую вещь он бронировал. Поправил, спасибо.

2023-03-11 01:24 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemBookingResponseDtoList.add(getItemBooking(itemFromDB.getId(), userId));
Понял. Переписал метод, вроде работает.

2023-03-11 01:49 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemBookingResponseDto> getItemsBooking(Long userId);
Вообще у меня задумка была следующая: 
чтобы в контроллере происходил перевод из ДТО в модель. Затем модель отправляется в сервис. Ответ из сервиса также возвращается в виде модели. И уже в контроллере происходит перевод из модели в ДТО.
Но в данных методах так сделать не получилось, т.к. поля lastbooking & nextbooking есть только ItemBookingResponseDto... В item таких полей нет.

2023-03-11 01:58 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        userService.getUserById(userId);
Задумка была следующая: 
1. Чтобы в контроллере происходил перевод из ДТО в модель. Затем модель отправляется в сервис. Ответ из сервиса также возвращается в виде модели. И уже в контроллере происходит перевод из модели в ДТО.

2. Также часто использую метод: **userService.getUserById(userId),** чтобы проверить на уровне контроллера, существует ли такой User.

3. Если в контроллере оставить только вызов метода из сервиса. А в сервисе уже устраивать все проверки и переводы из ДТО в модель и обратно, то получается, что контроллер будет пропускать несуществующих User.
Это нормально? Если это ок, то давай я лучше поправлю этот момент.

2023-03-11 02:11 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        BookingState stateBooking = Objects.isNull(state) ? BookingState.ALL : BookingState.of(state);
Сделано! спасибо

2023-03-11 02:18 UTC, Anarmard commented
Александр, спасибо за комментарии! Поправил почти везде. По оставшимся опциональным вопросам есть сомнения как лучше сделать.

2023-03-11 08:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        userService.getUserById(userId);
3. Да, это ок. Обычно контроллеры валидируют данные, но не всегда с запросами к базе, это можно оставить на сервис

2023-03-11 20:27 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        userService.getUserById(userId);
Облегчил по максимуму все контроллеры, перевел всё в сервисы

2023-03-12 06:56 UTC, alexache requested changes

2023-03-12 06:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        ItemBookingResponseDto currentItem = itemService.getItemBooking(bookingCreateRequestDto.getItemId(), userId);
На будущее так же стоит придерживаться такого подхода;
 - контроллеры взаимодействуют с сервисами
 - сервисы принимают/возвращают ДТО (это опционально, контроллер тоже может использовать маппер. но единообразно)
 - сервисы взаимодействуют с репозиториями (потому что сервисы возвращают ДТО, но самим сервисам удобнее работать с моделями)

2023-03-12 06:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        currentBooking.setItem(itemMapper.toItem(currentItem, currentItem.getOwner().getId()));
Вот здесь получается лишний вызов маппера - выше в сервисе вещей была сделана обратная конвертациия модели в дто, а здесь уже обратно, это лишняя работа. Если бы сервис бронирований работал с репозиторием вещей, такой проблемы бы не было

2023-03-12 06:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreateRequestDto.java
>      private Item item;
Это осталось в виде модели, почему бы не изменить на ДТО?

2023-03-12 06:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            for (Booking currentLastBooking : lastListBooking) {
Не очень оптимальный способ с проходом списка во вложенном цикле. Это квадратичная сложность, то есть довольно медленно с ростом размера списка. Как можно сделать иначе? Переложить сначала last/next booking в мапы единственным проходом по списку, это будет линейная сложность

2023-03-12 06:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public User getUserById(Long userId) {
Это получается приватный метод?

2023-03-12 06:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            User u = repository.findUserByEmail(user.getEmail());
Зачем второй раз одинаковый запрос к базе? Можно с первого раза сохранить результат?

2023-03-12 14:23 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            User u = repository.findUserByEmail(user.getEmail());
Точно)) что-то опять затупил...

2023-03-12 14:24 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public User getUserById(Long userId) {
Да, спасибо, поправил!

2023-03-12 14:36 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreateRequestDto.java
>      private Item item;
Да, извини. Вроде смотрел все дто по данному вопросу, но проглядел((

2023-03-12 15:15 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            for (Booking currentLastBooking : lastListBooking) {
Понял в чем проблема, но не уверен, что понял, как надо правильно сделать) Посмотри, пожалуйста. Вроде нет теперь цикла в цикле. 
Можно наверное еще через стрим наверное передать из List в Map.

2023-03-12 15:47 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        currentBooking.setItem(itemMapper.toItem(currentItem, currentItem.getOwner().getId()));
см. мой предыдущий комментарий. Не понимаю как в данном случае обойтись без ItemSerivceImpl...

2023-03-12 15:47 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        ItemBookingResponseDto currentItem = itemService.getItemBooking(bookingCreateRequestDto.getItemId(), userId);
Александр, по поводу пункта 3 такой вопрос на примере getItemBooking: 
в этом методе не только обращение к репозитарию ItemRepository, но и много других проверок, циклов и т.д.... Не понимаю, как в данном случае сервису BookingServiceImpl взаимодействовать с ItemRepository, а не с ItemServiceImpl.. 
Или я не понял комментарий

2023-03-12 15:47 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        ItemBookingResponseDto currentItem = itemService.getItemBooking(bookingCreateRequestDto.getItemId(), userId);
Я поправлю данный момент до merge

2023-03-13 23:14 UTC, alexache approved these changes

2023-03-19 14:56 UTC, Anarmard commented
В следующей версии переделать:
Сервисы должны вызывать репозиторий, а не другой сервис, если необходимо получить данные.

2023-03-19 14:56 UTC, merged