v3.1
Anarmard/java-shareit pull request #3
Opened 2023-03-26 01:06 UTC by Anarmard

- Add ItemRequest (Controller, Service, Repository)
- Pageable for all GET methods
- Without tests

2023-03-28 20:00 UTC, alexache requested changes

2023-03-28 20:00 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Модификаторов доступа не хватает

2023-03-28 20:00 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(status().isOk());
Суть подхода к тесту верная, только не помешает еще верификация в конце через Mockito.verify() на то что сервис был вызван и нужное количество раз

2023-03-28 20:00 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.start",
(опционально) не обязательно прямо все-все поля проверять, можно ограничиться основными

2023-03-28 20:00 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +                        .header("X-Later-User-Id", 1L)
Странный хедер

2023-03-29 23:54 UTC, Anarmard commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Спасибо, поправил!

2023-03-29 23:54 UTC, Anarmard commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(status().isOk());
Добавил, спасибо!

2023-03-29 23:55 UTC, Anarmard commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.start",
Хорошо)

2023-03-29 23:55 UTC, Anarmard commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +                        .header("X-Later-User-Id", 1L)
)) исправил здесь и в самом контроллере (я так понимаю этот эндпоинт не нужен был, лишний).

2023-04-02 07:58 UTC, felixoff commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestHeader("X-Sharer-User-Id") Long userId,
Хедеры можно вынести в отдельную переменную для избежания дубляжей

2023-04-02 07:58 UTC, felixoff commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateRequestDto.java
>      private LocalDateTime start; // дата и время начала бронирования
Вместо множественных private лучше использовать @FieldDefaults

2023-04-02 07:58 UTC, felixoff commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplTest.java
> +        Assertions.assertEquals("User with such ID does not exist", e0.getMessage());
Лучше указывать в комментариях пользователю конкретный идентификатор

2023-04-02 14:30 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateRequestDto.java
>      private LocalDateTime start; // дата и время начала бронирования
Спасибо большое, не знал про такую аннотацию! Во всех dto и model указал ее.

2023-04-02 14:56 UTC, Anarmard commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplTest.java
> +        Assertions.assertEquals("User with such ID does not exist", e0.getMessage());
Понял, спасибо. Поправил, где применимо.

2023-04-02 15:23 UTC, Anarmard commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestHeader("X-Sharer-User-Id") Long userId,
ОК. Надеюсь я верно сделал то, что ты просил (в переменную засунул только название заголовка... как весь заголовок через переменную сделать, не знаю и не смог найти такую инфу): 
private static final String USERID = "X-Sharer-User-Id";

2023-04-02 21:07 UTC, merged