v4.1
Anarmard/java-shareit pull request #4
Opened 2023-04-10 00:21 UTC by Anarmard

docker
- структура
- dockerfile / docker-compose

2023-04-11 20:30 UTC, alexache requested changes

2023-04-11 20:30 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareitgateway/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of(
Мапу из одного элемента можно убирать и делать простую подстановку в URI

2023-04-11 20:30 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareitgateway/booking/BookingController.java
> +        return bookingClient.approve(userId, bookingId, approved);
Лучше логгирование оставить для всех методов контроллера

2023-04-11 20:30 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareitgateway/item/ItemController.java
> +        return itemClient.add(userId, itemCreateDto);
Логгирование

2023-04-11 20:30 UTC, alexache commented on pom.xml
> -
Зачем все эти зависимости родительскому модулю? Может подразумевается dependencyManagement для выставление нужных версий? В остальном, у моделей разные зависимости

2023-04-11 20:30 UTC, alexache commented on server/src/main/java/ru/practicum/shareitserver/booking/controller/BookingController.java
> +                                          @Valid @RequestBody BookingCreateRequestDto bookingCreateRequestDto) {
Никаких валидаций не должно оставаться в модуле сервера. Из-за путаница с зависимостями родительского модуля это не так очевидно

2023-04-12 07:53 UTC, Anarmard commented on gateway/src/main/java/ru/practicum/shareitgateway/booking/BookingController.java
> +        return bookingClient.approve(userId, bookingId, approved);
Поправил, спасибо

2023-04-12 07:53 UTC, Anarmard commented on gateway/src/main/java/ru/practicum/shareitgateway/item/ItemController.java
> +        return itemClient.add(userId, itemCreateDto);
Прошелся по всем контроллерам, поправил. Спасибо

2023-04-12 08:12 UTC, Anarmard commented on server/src/main/java/ru/practicum/shareitserver/booking/controller/BookingController.java
> +                                          @Valid @RequestBody BookingCreateRequestDto bookingCreateRequestDto) {
Да, вот сомневался удалять их или нет. 
Наверное надо удалить и другие проверки, которые у меня есть в BookingService модуль server?  Так как все эти проверки теперь есть в модуле gateway

2023-04-12 08:22 UTC, Anarmard commented on pom.xml
> -
Александр, pom наверное мое самое слабое место, которое я не понимаю(( Просто добавляю все зависимости, которые когда либо были у меня в проекте. Но в данном конкретном случае - это наверное сыграло со мной злую шутку: тесты не проходят возможно как раз из-за этого. 

Сейчас попробую удалить эти зависимости.

2023-04-12 10:13 UTC, Anarmard commented on pom.xml
> -
Убрал еще валидацию из dto

2023-04-12 23:47 UTC, Anarmard commented
Александр, спасибо тебе огромное за подсказку!!! Удалил лишнее из родительского pom и ситуация исправилась.

2023-04-13 19:52 UTC, alexache commented on server/src/main/java/ru/practicum/shareitserver/booking/controller/BookingController.java
> +                                          @Valid @RequestBody BookingCreateRequestDto bookingCreateRequestDto) {
Все дублирующие проверки (и в целом проверки без использования базы) нужно убрать, верно

2023-04-13 19:59 UTC, alexache approved these changes

2023-04-13 23:28 UTC, merged